FORMAT: 1A
HOST: http://api-navetest.herokuapp.com

# api-navetest

API de um produto para organização de campeonatos de tênis de mesa.

## Users Collection [/users]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "id": "a06ffb0c-c722-4bc2-945b-d56a4f4b4ee1",
                "name": "Matheus Danemberg",
                "email": "matheus@nave.rs",
                "role_id": "526775d4-7f17-4432-8c74-466e2f25d501",
                "created_at": "2018-10-15T14:03:39.081Z",
                "updated_at": "2018-10-15T14:03:39.081Z",
                "role": {
                    "id": "526775d4-7f17-4432-8c74-466e2f25d501",
                    "name": "player"
                }
            }
        ]

### Create a New User [POST]


+ Request (application/json)

        {
            "email": "juju2@nave.rs",
            "name": "Juliano Reis",
            "password": "juju123",
            "role_id": "526775d4-7f17-4432-8c74-466e2f25d501"
        }

+ Response 200 (application/json)

    + Body

            {
                "id": "7b5d6d36-1a65-4b80-9638-f6c40793d838",
                "name": "Juliano Reis",
                "email": "juju2@nave.rs",
                "role_id": "526775d4-7f17-4432-8c74-466e2f25d501",
                "created_at": "2018-10-16T12:39:16.122Z",
                "updated_at": "2018-10-16T12:39:16.122Z",
                "role": {
                    "id": "526775d4-7f17-4432-8c74-466e2f25d501",
                    "name": "player"
                }
            }

## Users By Id Collection [/users/{id}]

### Update a User [PUT]

+ Request (application/json)

        {
            "email":"gustavo2@nave.rs",
            "name":"Gustavo Pinho",
            "password":"gustavo123",
            "role_id":"526775d4-7f17-4432-8c74-466e2f25d501"
        }

+ Response 200 (application/json)

        {
            "id": "7b5d6d36-1a65-4b80-9638-f6c40793d838",
            "name": "Gustavo Pinho",
            "email": "gustavo2@nave.rs",
            "role_id": "526775d4-7f17-4432-8c74-466e2f25d501",
            "created_at": "2018-10-16T12:39:16.122Z",
            "updated_at": "2018-10-16T12:57:42.229Z"
        }

### Delete a User [DELETE]

+ Parameters
    
    + id: 7b5d6d36-1a65-4b80-9638-f6c40793d838 (uuid)

+ Response 200 (application/json)

        {
            "name": "Deleted",
            "message": "Successfully deleted",
            "deleted": true,
            "statusCode": 200,
            "errorCode": 200
        }

## Championship Collection [/championships]

### List all championships

+ Response 200 (application/json)

    [
        {
            "id": "9c946cdf-c47e-40ac-ae1d-016f19f13b77",
            "name": "Taça",
            "created_at": "2018-10-15T14:05:31.742Z",
            "updated_at": "2018-10-15T14:06:47.132Z",
            "users": [
                        {
                            "id": "a06ffb0c-c722-4bc2-945b-d56a4f4b4ee1",
                            "name": "Matheus Danemberg",
                            "email": "matheus@nave.rs",
                            "role_id": "526775d4-7f17-4432-8c74-466e2f25d501",
                            "created_at": "2018-10-15T14:03:39.081Z",
                            "updated_at": "2018-10-15T14:03:39.081Z"
                        }
                    ]
        }
    ]